export const breakfastItems = [
  { id: 1, image: "items/1.webp", title: "經典鬆餅", price: 8.99 },
  { id: 2, image: "items/2.webp", title: "班尼迪克蛋", price: 10.49 },
  { id: 3, image: "items/3.webp", title: "酪梨吐司", price: 6.75 },
  { id: 4, image: "items/4.webp", title: "法式吐司", price: 9.25 },
  { id: 5, image: "items/5.webp", title: "芝士煎蛋餅", price: 7.99 },
  { id: 6, image: "items/6.webp", title: "培根煎蛋", price: 8.75 },
  { id: 7, image: "items/7.webp", title: "煙燻三文魚貝果", price: 11.5 },
  { id: 8, image: "items/8.webp", title: "希臘優格芭菲", price: 9.99 },
  { id: 9, image: "items/9.webp", title: "純素早餐捲", price: 7.25 },
  { id: 10, image: "items/10.webp", title: "肉桂捲", price: 5.49 },
  { id: 11, image: "items/21.webp", title: "榛果巧克力薄餅", price: 12.99 },
  { id: 12, image: "items/22.webp", title: "巴西莓碗", price: 9.5 },
  { id: 13, image: "items/23.webp", title: "英式早餐", price: 11.99 },
  { id: 14, image: "items/24.webp", title: "菠菜芝士餡餅", price: 7.25 },
  { id: 15, image: "items/25.webp", title: "香蕉鬆餅", price: 5.99 },
  { id: 16, image: "items/26.webp", title: "早餐玉米餅", price: 6.49 },
];
